### ISSUE TITLE
warning: build failed, waiting for other jobs to finish...

### ISSUE THREAD

**Issue by kqmeta** [RadonCoding/discoon#14]
when i try to build i get this.

  --- stderr
  thread 'main' panicked at '
  failed to execute command: program not found
  is `cmake` not installed?

  build script failed, must exit now', C:\Users\sex\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.48\src\lib.rs:975:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

I also dont know how to put the webhost in the script

**Comment by RadonCoding** [comment]
is cmake not installed?

**Comment by RadonCoding** [comment]
> I also dont know how to put the webhost in the script

u put it in public_html directory

**Comment by kqmeta** [comment]
cmake wasn't installed. then i installed it but still same error
and i put the upload.php file in public_html, but what do i put here?
![image](https://user-images.githubusercontent.com/94103858/190399288-deb8aba1-bb69-4008-bb96-13699133012f.png)

**Comment by RadonCoding** [comment]
> cmake wasn't installed. then i installed it but still same error and i put the upload.php file in public_html, but what do i put here? ![image](https://user-images.githubusercontent.com/94103858/190399288-deb8aba1-bb69-4008-bb96-13699133012f.png)

your cmake is not in the environment path variable and the path of the script e.g "https://site-name.000webhostapp.com/upload.php"

**Comment by kqmeta** [comment]
i hope im not annoying you but i dont know much about coding i only know lua. How do i put my cmake in the environment path variable and what is the environment path variable

**Comment by RadonCoding** [comment]
how did you install CMake

**Comment by kqmeta** [comment]
i went to their website and downloaded it

**Comment by RadonCoding** [comment]
did u close and re-open vscode afterwards

**Comment by kqmeta** [comment]
vscode isn't open tho 💀

**Comment by kqmeta** [comment]
do i have to open it?

**Comment by RadonCoding** [comment]
did u re-open the terminal after installing cmake?

**Comment by kqmeta** [comment]
cmd? yes i did

**Comment by RadonCoding** [comment]
where did u install cmake to

**Comment by kqmeta** [comment]
idk i just clicked next without looking 🗿

**Comment by kqmeta** [comment]
ok i reinstalled it to the discoon folder

**Comment by kqmeta** [comment]
oh now it says it cant find visual studio 
do i have to run the command in vs?

**Comment by RadonCoding** [comment]
...

**Comment by RadonCoding** [comment]
u just need the folder containing cmake in the environment path

**Comment by kqmeta** [comment]
yes and now its giving me this error
  --- stderr
  CMake Error at CMakeLists.txt:2 (project):
    Generator

      Visual Studio 17 2022

    could not find any instance of Visual Studio.

**Comment by RadonCoding** [comment]
so install visual studio then

**Comment by kqmeta** [comment]
its already open tho.

**Comment by kqmeta** [comment]
i tried with vs code, visual studio 2019 and visual studio 2022 and it gives the same error

**Comment by kqmeta** [comment]
oh it works i had to enable some stuff

**Comment by kqmeta** [comment]
oh it works i had to enable some stuff

**Comment by kqmeta** [comment]
Heyyy

**Comment by kqmeta** [comment]
where does the stub save

**Comment by RadonCoding** [comment]
> where does the stub save

this is the kind of question you can google (./target/release)

**Comment by kqmeta** [comment]
thx i found it but it doenst open

**Comment by kqmeta** [comment]
and it doesnt send stuff to my webhook either

**Comment by kqmeta** [comment]
hi can you help pls

**Comment by kqmeta** [comment]
it doesnt open and doesnt send anything to the webhook
