### ISSUE TITLE
suggestions + issues (ive faced)

### ISSUE THREAD

**Issue by PixGuy** [RadonCoding/discoon#17]
hi there, I've stumbled upon this project, and I thought it was pretty interesting, but, I think it could be better, here are some suggestions:
1 - make a Telegram or a matrix.org chatroom (discord is kinda useless since it will term the server in like a week)
2 - make a pre-compiled binary, those who don't understand Rust or how to use Cargo will have lots of issues compiling
3 - add some more details to the tutorial (images speak for 1000 words) 
4 - mention all dependencies, I've noticed you forgot to mention you need CMake for this to work...
issues I've faced and I think others can too:
- what tf are we supposed to do with upload.php after uploading it to the WebHost? (how I solved it: I checked the src and learned what the file did)
- where is the compiled binary? (I haven't faced this issue myself but I feel like others can face this too, It can be solved either using suggestions 2 or 3)
have a good one!

**Comment by RadonCoding** [comment]
you're free to contribute if u want this stuff done the instructions are clear enough already though you do need basic technical skills

**Comment by ilyigna** [comment]
> 1 - make a Telegram or a matrix.org chatroom (discord is kinda useless since it will term the server in like a week)
not really worth it

> 2 - make a pre-compiled binary, those who don't understand Rust or how to use Cargo will have lots of issues compiling
just read the readme smh (+ a pre-compiled binary may lead issues)

> 4 - mention all dependencies, I've noticed you forgot to mention you need CMake for this to work...
i believe `cargo build` says u this

**Comment by RadonCoding** [comment]
![image](https://user-images.githubusercontent.com/86915746/209845165-94603267-8bae-486d-a31d-209f5ef8541a.png)
