### ISSUE TITLE
leveldb-sys v2.0.9 not building

### ISSUE THREAD

**Issue by DestroyersTaken** [RadonCoding/discoon#20]
Not sure why this is happening i have cmake pathed and still does not want to work. Can you help?

![aaaaa](https://user-images.githubusercontent.com/82193530/193697346-e5a6c7d2-2d49-4668-a4ab-b2d63f7757f4.PNG)

**Comment by RadonCoding** [comment]
yeah it's because of ur folder structure

**Comment by RadonCoding** [comment]
u have a folder named discoon inside a folder named discoon that causes it to fail

**Comment by DestroyersTaken** [comment]
Ok i will pull out the one discoon out of the other when i get to my house.

**Comment by DestroyersTaken** [comment]
Well i did it but i got a bigger error
![more](https://user-images.githubusercontent.com/82193530/193902873-86e5b8a1-4e13-4b9e-aba2-164476d8717a.PNG)
![err](https://user-images.githubusercontent.com/82193530/193902875-6eaa9fdd-a905-4560-b9a6-e3e02ae88e67.PNG)
![eeaa](https://user-images.githubusercontent.com/82193530/193902876-ccdd46be-a4ea-41f1-ad58-7fda0be70ecf.PNG)
![aaa](https://user-images.githubusercontent.com/82193530/193902877-9f30a7f9-380c-4017-a007-aebd357adec0.PNG)

**Comment by RadonCoding** [comment]
Make a issue to leveldb-sys not me

**Comment by DestroyersTaken** [comment]
Ok
