### ISSUE TITLE
"failed to run custom build command for `mozjpeg-sys v0.10.13`"

### ISSUE THREAD

**Issue by Aritz331** [RadonCoding/discoon#4]
![image](https://user-images.githubusercontent.com/59333567/179623614-2d2f4b4e-421b-4248-bade-df067db76463.png)

**Comment by Aritz331** [comment]
ignore the warning, nasm wasnt in path
mozjpeg error log (stderr):

>   --- stderr
>
>
>  error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O1" "-Brepro" "-I" "D:\\USUARIO\\Downloads\\discoon-main\\discoon-main\\target\\release\\build\\mozjpeg-sys-2cd18dba427a592f\\out\\include" "-I" "C:\\Users\\USER\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\mozjpeg-sys-0.10.13\\vendor" "-I" "C:\\Users\\USER\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\mozjpeg-sys-0.10.13\\vendor\\simd" "-FoD:\\USUARIO\\Downloads\\discoon-main\\discoon-main\\target\\release\\build\\mozjpeg-sys-2cd18dba427a592f\\out\\vendor/jdatadst.o" "-c" "vendor/jdatadst.c" with args "cl.exe" did not execute successfully (status code exit code: 0xc0000005).

**Comment by Aritz331** [comment]
![image](https://user-images.githubusercontent.com/59333567/179625275-def62b2e-2db1-4142-b0e8-20ac375c8b7c.png)

**Comment by RadonCoding** [comment]
This isn't a issue with discoon this is a issue with a crate.

**Comment by Aritz331** [comment]
ok and how do i fix it
