### ISSUE TITLE
proc macro panicked

### ISSUE THREAD

**Issue by GreenShadowLegend** [RadonCoding/discoon#9]
![proc_macro_panicked](https://user-images.githubusercontent.com/98899162/182626527-c943bd21-12fd-4112-af91-94d30dac5b10.png)

**Comment by RadonCoding** [comment]
Remove the []

**Comment by RadonCoding** [comment]
from the encrypt!

**Comment by RadonCoding** [comment]
i'll update discoon today and make it easier for people to use it

**Comment by GreenShadowLegend** [comment]
in the lib.rs ?

**Comment by RadonCoding** [comment]
your webhook has brackets around it

**Comment by GreenShadowLegend** [comment]
![wafawdawf](https://user-images.githubusercontent.com/98899162/182628599-a7ac5a3e-247f-4ce5-8132-be6606d02c53.png)

**Comment by RadonCoding** [comment]
what did u put as ur encryption key ;)

**Comment by GreenShadowLegend** [comment]
![enc](https://user-images.githubusercontent.com/98899162/182636701-91f0658d-129f-4e2c-a673-790303a5075a.png)

**Comment by RadonCoding** [comment]
are u sure those are valid?

**Comment by GreenShadowLegend** [comment]
I generated a 256-bit key, converted it to base64 and put it in key_bites, then i generated a 128-bit key, converted it to base64 and put it in the iv_bytes

**Comment by RadonCoding** [comment]
just pushed new changes

**Comment by RadonCoding** [comment]
read the new instructions and have fun

**Comment by GreenShadowLegend** [comment]
ok, thx

**Comment by RadonCoding** [comment]
yeah your webhost and the path to the upload.php file e.g https://webhost.com/upload.php

**Comment by GreenShadowLegend** [comment]
![image](https://user-images.githubusercontent.com/98899162/182641017-92aa764f-bd19-4749-af13-9f015ec56baa.png)

**Comment by RadonCoding** [comment]
ah fuck forgot that

**Comment by RadonCoding** [comment]
just remove the dependency

**Comment by GreenShadowLegend** [comment]
from where?

**Comment by RadonCoding** [comment]
Cargo.toml

**Comment by GreenShadowLegend** [comment]
it works, and in the target/release folder, the only thing that I need to send is discoon.exe?

**Comment by GreenShadowLegend** [comment]
also I noticed that even tho I set everything on true in constants.rs it only gives me the ip, token and login details. It doesnt give any browser passwords, cookies, history or any screenshot

**Comment by RadonCoding** [comment]
interesting

**Comment by RadonCoding** [comment]
did you save the constants.rs

**Comment by RadonCoding** [comment]
ctrl + s

**Comment by GreenShadowLegend** [comment]
yes, discord even restarts, so that works

**Comment by RadonCoding** [comment]
that shouldn't be possible

**Comment by GreenShadowLegend** [comment]
is it detected? by the windows antivirus?

**Comment by RadonCoding** [comment]
yes

**Comment by GreenShadowLegend** [comment]
is it because it gets blocked by the antivirus?

**Comment by GreenShadowLegend** [comment]
ok, thx, everything else works fine
